name: Life
description: A customizable implementation of Conways Game of Life
dependencies:
  polymer: ">=0.15.1 <0.16.0"
  core_elements: ">=0.6.0"
  paper_elements: ">=0.6.0"
dev_dependencies:
  unittest: ">=0.10.0"
transformers:
- polymer
